vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: '%app.path.candidate_cvs%'
            upload_destination: '%kernel.project_dir%/public%app.path.candidate_cvs%'
